### ISSUE TITLE
Can not navigate to definition

### ISSUE THREAD

**Issue by crbelaus** [crbelaus/vscode-elixir#2]
The definition provider is failing when trying to navigate to a module or function definition.

The following error appears in the debug console:

```
rejecting TypeError: result.lastIndexOf is not a function
elixirSenseDefinitionProvider.ts:57
    at __dirname.provideDefinition.resultPromise.then.then.then.result (/Users/crbelaus/Projects/vscode-elixir/src/elixirSenseDefinitionProvider.ts:46:55)
    at <anonymous>
rejecting TypeError: result.lastIndexOf is not a function
elixirSenseDefinitionProvider.ts:57
    at __dirname.provideDefinition.resultPromise.then.then.then.result (/Users/crbelaus/Projects/vscode-elixir/src/elixirSenseDefinitionProvider.ts:46:55)
    at <anonymous>
```

**Comment by crbelaus** [comment]
Closed in c7d0e72106dcb4d653712ce982dabb32d6325338
